remote_theme: b2a3e8/jekyll-theme-console

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

title: AI Notepad
description: My personal notepad
baseurl: /ai-notepad-block
url: https://kaiqueramos.github.io

header_pages:
  - index.md
  - about.md

style: dark
